name: Predict
on:
  workflow_dispatch:
    inputs:
      backend_url: { description: "Backend URL", required: true }
      api_key:     { description: "API key", required: true }
      year:        { required: true, default: "2025" }
      round:       { required: true }
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Write prediction
        run: |
          curl -s -X POST "${{ inputs.backend_url }}/predict" \
            -H "Content-Type: application/json" \
            -H "X-API-Key: ${{ inputs.api_key }}" \
            -d "{\"year\":${{ inputs.year }},\"round\":${{ inputs.round }},\"persist\":true}"
