name: Update Results
on:
  workflow_dispatch:
    inputs:
      backend_url: { required: true }
      api_key:     { required: true }
      year:        { required: true, default: "2025" }
      round:       { required: true }
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Retry until Ergast data is ready (max ~36h)
        run: |
          for i in {1..12}; do
            curl -s -X POST "${{ inputs.backend_url }}/update_results" \
              -H "Content-Type: application/json" \
              -H "X-API-Key: ${{ inputs.api_key }}" \
              -d "{\"year\":${{ inputs.year }},\"round\":${{ inputs.round }}}" && break
            sleep 10800  # 3h
          done
